version: '3.5'
services:
  postgres:
    ports:
      - '5436:5432' # 5436 <- change this value
    restart: always
    image: postgres:9.6.5-alpine
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
